//! Build script for the kernel crate.
//!
//! When the `embed_initramfs` / `embed_minixfs` features are active and the
//! target is one of the MINIX triples, assembles the initramfs CPIO archive
//! and the MinixFS root image from the already-built userland/server
//! binaries in `target/<triple>/release/`, then emits the generated include
//! stubs via `cargo:rustc-env` (the kernel sources include them through
//! `env!("INITRAMFS_DATA")` / `env!("MINIXFS_DATA")`).
//!
//! The binaries are built by the top-level Just recipes (plain `cargo build
//! -p userland -p servers`); this script never invokes cargo itself (a
//! build script calling cargo against the same target dir would deadlock on
//! the cargo lock, and a disjoint dir would throw away the build cache).

use std::env;
use std::path::{Path, PathBuf};

use boot_image::{cpio, manifest, minixfs, targets};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace = manifest_dir.join("../..");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let embed_initramfs = env::var("CARGO_FEATURE_EMBED_INITRAMFS").is_ok();
    let embed_minixfs = env::var("CARGO_FEATURE_EMBED_MINIXFS").is_ok();
    if !embed_initramfs && !embed_minixfs {
        return;
    }

    let rustc_target = env::var("TARGET").unwrap_or_default();
    match targets::target_from_rustc_target(&rustc_target) {
        Some(t) => assemble(&t, &workspace, &out_dir, embed_initramfs, embed_minixfs),
        None => {
            // Host/foreign build with an embed feature on (e.g. `cargo test
            // --all-features`): emit empty stubs so the includes compile.
            if embed_initramfs {
                write_initramfs_stub(&out_dir, 0);
                emit_env("INITRAMFS_DATA", &out_dir.join("initramfs_data.rs"));
                emit_env("INITRAMFS_CPIO", &out_dir.join("initramfs.cpio"));
            }
            if embed_minixfs {
                write_minixfs_stub(&out_dir, 0);
                emit_env("MINIXFS_DATA", &out_dir.join("minixfs_data.rs"));
                emit_env("MINIXFS_IMG", &out_dir.join("minixfs.img"));
            }
        }
    }
}

fn assemble(
    t: &targets::BuildTarget,
    workspace: &Path,
    out_dir: &Path,
    embed_initramfs: bool,
    embed_minixfs: bool,
) {
    let release = targets::release_dir(t, workspace);

    // Read the boot binaries from the shared release dir (built by the
    // top-level `just build <target>` recipes).
    let mut bins = Vec::new();
    for &(dest, bin_name) in manifest::BOOT_BINS {
        // The C smoke-test binaries (helloc/ctest) are only built for
        // x86_64 today (tools/build-c-hello.py is x86-only); skip them on
        // other arches until the build script grows target support.
        if matches!(dest, "/bin/helloc" | "/bin/ctest") && t.arch != "x86_64" {
            continue;
        }
        let src = release.join(bin_name);
        let data = match std::fs::read(&src) {
            Ok(d) => d,
            Err(e) => panic!(
                "kernel build.rs: boot binary {} missing ({e}). \
                 Build the userland binaries first, e.g. `just build {}`.",
                src.display(),
                t.arch
            ),
        };
        bins.push((dest, data));
        // Re-run this script when the binary changes so the images and the
        // kernel are rebuilt accordingly.
        println!("cargo:rerun-if-changed={}", src.display());
    }

    // Mirror the assembled images to a stable, per-target path for host
    // inspection (e.g. `od -A x target/images/x86_64-pc-minix/minixfs.img`).
    let mirror_dir = workspace.join("target").join("images").join(t.out_dir);

    if embed_initramfs {
        let cpio_bytes = cpio::standard_initramfs(&bins);
        let cpio_path = out_dir.join("initramfs.cpio");
        write_if_changed(&cpio_path, &cpio_bytes);
        write_initramfs_stub(out_dir, cpio_bytes.len());
        emit_env("INITRAMFS_DATA", &out_dir.join("initramfs_data.rs"));
        emit_env("INITRAMFS_CPIO", &cpio_path);
        copy_mirror(&mirror_dir.join("initramfs.cpio"), &cpio_bytes);
    }

    if embed_minixfs {
        let img_bytes = minixfs::build_minixfs(&bins);
        let img_path = out_dir.join("minixfs.img");
        write_if_changed(&img_path, &img_bytes);
        write_minixfs_stub(out_dir, img_bytes.len());
        emit_env("MINIXFS_DATA", &out_dir.join("minixfs_data.rs"));
        emit_env("MINIXFS_IMG", &img_path);
        copy_mirror(&mirror_dir.join("minixfs.img"), &img_bytes);
    }
}

fn emit_env(name: &str, path: &Path) {
    println!("cargo:rustc-env={name}={}", path.display());
}

fn write_initramfs_stub(out_dir: &Path, len: usize) {
    let rs = format!(
        concat!(
            "// Auto-generated by crates/kernel/build.rs — DO NOT EDIT\n",
            "#[allow(dead_code)]\n",
            "#[allow(unused_attributes)]\n",
            "#[unsafe(link_section = \".initramfs\")]\n",
            "#[used]\n",
            "pub static INITRAMFS_CPIO: [u8; {len}] = *include_bytes!(concat!(env!(\"INITRAMFS_CPIO\")));\n",
            "pub const INITRAMFS_CPIO_LEN: usize = {len};\n",
        ),
        len = len,
    );
    write_if_changed(&out_dir.join("initramfs_data.rs"), rs.as_bytes());
}

fn write_minixfs_stub(out_dir: &Path, len: usize) {
    let rs = format!(
        concat!(
            "// Auto-generated by crates/kernel/build.rs — DO NOT EDIT\n",
            "#[allow(dead_code)]\n",
            "#[allow(unused_attributes)]\n",
            "#[unsafe(link_section = \".minixfs\")]\n",
            "#[used]\n",
            "pub static MINIXFS_IMG: [u8; {len}] = *include_bytes!(concat!(env!(\"MINIXFS_IMG\")));\n",
            "pub const MINIXFS_IMG_LEN: usize = {len};\n",
        ),
        len = len,
    );
    write_if_changed(&out_dir.join("minixfs_data.rs"), rs.as_bytes());
}

fn write_if_changed(path: &Path, data: &[u8]) {
    if let Ok(existing) = std::fs::read(path)
        && existing == data
    {
        return;
    }
    std::fs::write(path, data).expect("kernel build.rs: failed to write output");
}

fn copy_mirror(dest: &Path, data: &[u8]) {
    if let Some(parent) = dest.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    write_if_changed(dest, data);
}
