//! Initramfs CPIO newc archive parser.
//!
//! Reads the embedded initramfs archive (built by `tools/mkinitramfs.rs`)
//! and provides `find_initramfs_file()` to locate files by path.
//!
//! The initramfs is embedded as a byte array in the `.initramfs` section
//! via the `INITRAMFS_CPIO` static generated by `mkinitramfs.rs`.

/// Magic for CPIO newc format.
const CPIO_NEWC_MAGIC: [u8; 6] = *b"070701";

/// CPIO newc header (110 bytes).
#[repr(C)]
#[derive(Debug, Clone, Copy)]
struct CpioHeader {
    magic: [u8; 6],
    ino: [u8; 8],
    mode: [u8; 8],
    uid: [u8; 8],
    gid: [u8; 8],
    nlink: [u8; 8],
    mtime: [u8; 8],
    filesize: [u8; 8],
    dev_major: [u8; 8],
    dev_minor: [u8; 8],
    rdev_major: [u8; 8],
    rdev_minor: [u8; 8],
    namesize: [u8; 8],
    check: [u8; 8],
}

impl CpioHeader {
    /// Parse the header from raw bytes. Returns None if the data is too small
    /// or the magic doesn't match.
    fn from_bytes(data: &[u8]) -> Option<&CpioHeader> {
        if data.len() < core::mem::size_of::<CpioHeader>() {
            return None;
        }
        let hdr = unsafe { &*(data.as_ptr() as *const CpioHeader) };
        if hdr.magic != CPIO_NEWC_MAGIC {
            return None;
        }
        Some(hdr)
    }

    fn ascii_to_u32(bytes: &[u8; 8]) -> u32 {
        let s = core::str::from_utf8(bytes).unwrap_or("00000000");
        u32::from_str_radix(s, 16).unwrap_or(0)
    }

    fn filesize(&self) -> u32 {
        Self::ascii_to_u32(&self.filesize)
    }

    fn namesize(&self) -> u32 {
        Self::ascii_to_u32(&self.namesize)
    }

    fn mode(&self) -> u32 {
        Self::ascii_to_u32(&self.mode)
    }
}

/// Pad `offset` to the next 4-byte boundary (CPIO alignment).
fn pad4(offset: usize) -> usize {
    (offset + 3) & !3
}

/// Find a file in the initramfs by absolute path.
///
/// Returns `Some((data_slice, mode))` if the file is found, or `None`.
///
/// The initramfs is embedded via the `INITRAMFS_CPIO` static in the
/// `.initramfs` section, generated by `tools/mkinitramfs.rs`.
pub fn find_initramfs_file(path: &str) -> Option<(&'static [u8], u32)> {
    let data = unsafe { initramfs_data() };
    parse_initramfs(data, path)
}

/// Parse initramfs data and find a file by path.
fn parse_initramfs(data: &[u8], path: &str) -> Option<(&'static [u8], u32)> {
    let mut offset = 0usize;
    while offset + core::mem::size_of::<CpioHeader>() <= data.len() {
        let hdr = CpioHeader::from_bytes(&data[offset..])?;

        // Check for trailer
        let namesize = hdr.namesize() as usize;
        let filesize = hdr.filesize() as usize;

        // Read filename after header
        let name_start = offset + core::mem::size_of::<CpioHeader>();
        let name_end = name_start + namesize;
        if name_end > data.len() {
            return None;
        }
        let name_bytes = &data[name_start..name_end];
        // Remove null terminator for comparison
        let name_len = name_bytes.iter().position(|&b| b == 0).unwrap_or(namesize);
        let entry_name = core::str::from_utf8(&name_bytes[..name_len]).ok()?;

        // Check for TRAILER!!!
        if entry_name == "TRAILER!!!" {
            return None;
        }

        if entry_name == path {
            // File found — return the data
            let data_start = pad4(name_end);
            let data_end = data_start + filesize;
            if data_end > data.len() {
                return None;
            }
            let file_data = &data[data_start..data_end];
            // Safety: the data lives in a static, so we can extend the lifetime
            let static_data =
                unsafe { core::slice::from_raw_parts(file_data.as_ptr(), file_data.len()) };
            return Some((static_data, hdr.mode()));
        }

        // Advance to next entry
        let entry_end = pad4(name_end) + filesize;
        offset = pad4(entry_end);
    }
    None
}

/// Accessor for the embedded initramfs data.
///
/// # Safety
///
/// The initramfs data is embedded in the `.initramfs` section of the
/// kernel binary. This function must only be called after kernel loading
/// is complete and the section is accessible.
// Stub initramfs linker symbols for builds without `embed_initramfs`.
// When `embed_initramfs` is active, the linker script (`minix-raw.ld`)
// defines these from the `.initramfs` section.  The stubs prevent
// unresolved symbol errors in dev/test builds.
#[cfg(not(feature = "embed_initramfs"))]
#[used]
#[unsafe(no_mangle)]
pub static __initramfs_start: u8 = 0;
#[cfg(not(feature = "embed_initramfs"))]
#[used]
#[unsafe(no_mangle)]
pub static __initramfs_end: u8 = 1;

unsafe fn initramfs_data() -> &'static [u8] {
    // The INITRAMFS_CPIO static is defined in the generated code
    // (target/initramfs_data.rs) and placed in the .initramfs section.
    //
    // We use extern block to reference the linker symbols:
    //   __initramfs_start, __initramfs_end
    //
    // These are defined in the kernel linker script (minix-raw.ld)
    // or by the stubs above if not using embed_initramfs.
    unsafe extern "C" {
        static __initramfs_start: u8;
        static __initramfs_end: u8;
    }

    let start = core::ptr::addr_of!(__initramfs_start) as usize;
    let end = core::ptr::addr_of!(__initramfs_end) as usize;
    let len = end.wrapping_sub(start);
    // With stubs: len = 1, which is < 110 (header size), so
    // parse_initramfs will return None gracefully.
    // Debug-profile servers produce ~42 MB initramfs. Allow up to 256 MB
    // (the full QEMU memory), which is the maximum the physical memory
    // allocator can address before we hit MMIO space.
    if len == 0 || len > 256 * 1024 * 1024 {
        return &[];
    }
    unsafe { core::slice::from_raw_parts(start as *const u8, len) }
}

#[cfg(test)]
#[allow(
    clippy::needless_range_loop,
    clippy::manual_is_multiple_of,
    clippy::items_after_test_module
)]
mod tests {
    use super::*;

    /// Build a minimal CPIO newc archive in a buffer with one file entry
    /// and a trailer. Returns a reference to the buffer data.
    fn build_cpio<'a>(path: &str, content: &[u8], mode: u32, buf: &'a mut [u8]) -> &'a [u8] {
        let hdr_size = core::mem::size_of::<CpioHeader>();

        // Build header fields as 8-char hex
        fn hex8(v: u32) -> [u8; 8] {
            let mut b = [0u8; 8];
            let hex = b"0123456789abcdef";
            for (i, b_byte) in b.iter_mut().enumerate() {
                let nibble = ((v >> ((7 - i) * 4)) & 0xF) as usize;
                *b_byte = hex[nibble];
            }
            b
        }

        let header = CpioHeader {
            magic: CPIO_NEWC_MAGIC,
            ino: hex8(1),
            mode: hex8(mode),
            uid: hex8(0),
            gid: hex8(0),
            nlink: hex8(1),
            mtime: hex8(0),
            filesize: hex8(content.len() as u32),
            dev_major: hex8(0),
            dev_minor: hex8(0),
            rdev_major: hex8(0),
            rdev_minor: hex8(0),
            namesize: hex8((path.len() + 1) as u32),
            check: hex8(0),
        };

        let mut pos = 0;

        // Write header
        let hdr_bytes =
            unsafe { core::slice::from_raw_parts(&header as *const _ as *const u8, hdr_size) };
        buf[pos..pos + hdr_size].copy_from_slice(hdr_bytes);
        pos += hdr_size;

        // Write filename (with NUL)
        buf[pos..pos + path.len()].copy_from_slice(path.as_bytes());
        pos += path.len();
        buf[pos] = 0;
        pos += 1;

        // Pad to 4 bytes
        while pos % 4 != 0 {
            buf[pos] = 0;
            pos += 1;
        }

        // Write content
        buf[pos..pos + content.len()].copy_from_slice(content);
        pos += content.len();

        // Pad content to 4 bytes
        while pos % 4 != 0 {
            buf[pos] = 0;
            pos += 1;
        }

        // Write TRAILER!!!
        let trailer_hdr = CpioHeader {
            magic: CPIO_NEWC_MAGIC,
            ino: hex8(0),
            mode: hex8(0),
            uid: hex8(0),
            gid: hex8(0),
            nlink: hex8(1),
            mtime: hex8(0),
            filesize: hex8(0),
            dev_major: hex8(0),
            dev_minor: hex8(0),
            rdev_major: hex8(0),
            rdev_minor: hex8(0),
            namesize: hex8(11), // "TRAILER!!!\0"
            check: hex8(0),
        };
        let t_bytes =
            unsafe { core::slice::from_raw_parts(&trailer_hdr as *const _ as *const u8, hdr_size) };
        buf[pos..pos + hdr_size].copy_from_slice(t_bytes);
        pos += hdr_size;

        // Write "TRAILER!!!\0" name
        let trailer_name = b"TRAILER!!!\0";
        buf[pos..pos + trailer_name.len()].copy_from_slice(trailer_name);
        pos += trailer_name.len();

        // Pad to 4 bytes
        while pos % 4 != 0 {
            buf[pos] = 0;
            pos += 1;
        }

        &buf[..pos]
    }

    #[test]
    fn test_header_size() {
        assert_eq!(core::mem::size_of::<CpioHeader>(), 110);
    }

    #[test]
    fn test_cpio_magic() {
        assert_eq!(&CPIO_NEWC_MAGIC, b"070701");
    }

    #[test]
    fn test_find_file_in_cpio() {
        let mut buf = [0u8; 1024];
        let data = build_cpio("/sbin/init", b"Hello, init!", 0o100755, &mut buf);

        let result = parse_initramfs(data, "/sbin/init");
        assert!(result.is_some());
        let (content, mode) = result.unwrap();
        assert_eq!(content, b"Hello, init!");
        assert!(mode & 0o100000 != 0); // regular file
    }

    #[test]
    fn test_find_missing_file_returns_none() {
        let mut buf = [0u8; 1024];
        let data = build_cpio("/sbin/init", b"data", 0o100755, &mut buf);

        let result = parse_initramfs(data, "/nonexistent");
        assert!(result.is_none());
    }

    #[test]
    fn test_multiple_entries() {
        let mut buf = [0u8; 2048];
        let mut pos = 0;

        // Helper to append a CPIO entry to buf
        fn append_entry(buf: &mut [u8], pos: &mut usize, path: &str, content: &[u8], mode: u32) {
            let hdr_size = core::mem::size_of::<CpioHeader>();
            fn hex8(v: u32) -> [u8; 8] {
                let mut b = [0u8; 8];
                let hex = b"0123456789abcdef";
                for i in 0..8 {
                    let nibble = ((v >> ((7 - i) * 4)) & 0xF) as usize;
                    b[i] = hex[nibble];
                }
                b
            }
            let header = CpioHeader {
                magic: CPIO_NEWC_MAGIC,
                ino: hex8(1),
                mode: hex8(mode),
                uid: hex8(0),
                gid: hex8(0),
                nlink: hex8(1),
                mtime: hex8(0),
                filesize: hex8(content.len() as u32),
                dev_major: hex8(0),
                dev_minor: hex8(0),
                rdev_major: hex8(0),
                rdev_minor: hex8(0),
                namesize: hex8((path.len() + 1) as u32),
                check: hex8(0),
            };
            let hdr_bytes =
                unsafe { core::slice::from_raw_parts(&header as *const _ as *const u8, hdr_size) };
            buf[*pos..*pos + hdr_size].copy_from_slice(hdr_bytes);
            *pos += hdr_size;
            buf[*pos..*pos + path.len()].copy_from_slice(path.as_bytes());
            *pos += path.len();
            buf[*pos] = 0;
            *pos += 1;
            // Pad to 4-byte boundary
            #[allow(clippy::manual_is_multiple_of)]
            while *pos % 4 != 0 {
                buf[*pos] = 0;
                *pos += 1;
            }
            buf[*pos..*pos + content.len()].copy_from_slice(content);
            *pos += content.len();
            #[allow(clippy::manual_is_multiple_of)]
            while *pos % 4 != 0 {
                buf[*pos] = 0;
                *pos += 1;
            }
        }

        append_entry(&mut buf, &mut pos, "/bin/cat", b"cat data", 0o100755);
        append_entry(&mut buf, &mut pos, "/sbin/init", b"init data", 0o100755);
        append_entry(&mut buf, &mut pos, "/bin/sh", b"sh data", 0o100755);

        // Add trailer
        let hdr_size = core::mem::size_of::<CpioHeader>();
        fn hex8(v: u32) -> [u8; 8] {
            let mut b = [0u8; 8];
            let hex = b"0123456789abcdef";
            for i in 0..8 {
                let nibble = ((v >> ((7 - i) * 4)) & 0xF) as usize;
                b[i] = hex[nibble];
            }
            b
        }
        let trailer_hdr = CpioHeader {
            magic: CPIO_NEWC_MAGIC,
            ino: hex8(0),
            mode: hex8(0),
            uid: hex8(0),
            gid: hex8(0),
            nlink: hex8(1),
            mtime: hex8(0),
            filesize: hex8(0),
            dev_major: hex8(0),
            dev_minor: hex8(0),
            rdev_major: hex8(0),
            rdev_minor: hex8(0),
            namesize: hex8(11),
            check: hex8(0),
        };
        let t_bytes =
            unsafe { core::slice::from_raw_parts(&trailer_hdr as *const _ as *const u8, hdr_size) };
        buf[pos..pos + hdr_size].copy_from_slice(t_bytes);
        pos += hdr_size;
        let trailer_name = b"TRAILER!!!\0";
        buf[pos..pos + trailer_name.len()].copy_from_slice(trailer_name);
        pos += trailer_name.len();
        while pos % 4 != 0 {
            buf[pos] = 0;
            pos += 1;
        }

        let data = &buf[..pos];

        // Find each entry
        let (c, _) = parse_initramfs(data, "/sbin/init").unwrap();
        assert_eq!(c, b"init data");
        let (c, _) = parse_initramfs(data, "/bin/cat").unwrap();
        assert_eq!(c, b"cat data");
        let (c, _) = parse_initramfs(data, "/bin/sh").unwrap();
        assert_eq!(c, b"sh data");
        assert!(parse_initramfs(data, "/nonexistent").is_none());
    }

    #[test]
    fn test_empty_initramfs_returns_none() {
        let data = [0u8; 0];
        assert!(parse_initramfs(&data, "/sbin/init").is_none());
    }

    #[test]
    fn test_bad_magic_returns_none() {
        let data = [0u8; 110]; // zeros, not valid CPIO magic
        assert!(parse_initramfs(&data, "/sbin/init").is_none());
    }

    #[test]
    fn test_pad4() {
        assert_eq!(pad4(0), 0);
        assert_eq!(pad4(1), 4);
        assert_eq!(pad4(3), 4);
        assert_eq!(pad4(4), 4);
        assert_eq!(pad4(5), 8);
    }

    #[test]
    fn test_trailer_stops_search() {
        let mut buf = [0u8; 512];
        // Build CPIO with just TRAILER!!!
        let hdr_size = core::mem::size_of::<CpioHeader>();
        fn hex8(v: u32) -> [u8; 8] {
            let mut b = [0u8; 8];
            let hex = b"0123456789abcdef";
            for i in 0..8 {
                let nibble = ((v >> ((7 - i) * 4)) & 0xF) as usize;
                b[i] = hex[nibble];
            }
            b
        }
        let trailer = CpioHeader {
            magic: CPIO_NEWC_MAGIC,
            ino: hex8(0),
            mode: hex8(0),
            uid: hex8(0),
            gid: hex8(0),
            nlink: hex8(1),
            mtime: hex8(0),
            filesize: hex8(0),
            dev_major: hex8(0),
            dev_minor: hex8(0),
            rdev_major: hex8(0),
            rdev_minor: hex8(0),
            namesize: hex8(11),
            check: hex8(0),
        };
        let t_bytes =
            unsafe { core::slice::from_raw_parts(&trailer as *const _ as *const u8, hdr_size) };
        buf[..hdr_size].copy_from_slice(t_bytes);
        buf[hdr_size..hdr_size + 11].copy_from_slice(b"TRAILER!!!\0");
        assert!(parse_initramfs(&buf, "/sbin/init").is_none());
    }

    #[test]
    fn test_hex8_format() {
        assert_eq!(super::hex8_helper_test(255), *b"000000ff");
        assert_eq!(super::hex8_helper_test(0), *b"00000000");
        assert_eq!(super::hex8_helper_test(0o100755), *b"000081ed");
    }
}

#[cfg(test)]
#[allow(clippy::needless_range_loop)]
fn hex8_helper_test(v: u32) -> [u8; 8] {
    let mut b = [0u8; 8];
    let hex = b"0123456789abcdef";
    for i in 0..8 {
        let nibble = ((v >> ((7 - i) * 4)) & 0xF) as usize;
        b[i] = hex[nibble];
    }
    b
}
