//! Embedded Minix V3 filesystem image — used by the RAM disk driver.
//!
//! The image is generated by `crates/kernel/build.rs`; the generated stub
//! (referenced through `MINIXFS_DATA`) defines `MINIXFS_IMG` and
//! `MINIXFS_IMG_LEN`.

/// Include the generated Minix FS image data.
///
/// The path comes from kernel/build.rs via cargo:rustc-env=MINIXFS_DATA.
#[cfg(feature = "embed_minixfs")]
mod generated {
    include!(concat!(env!("MINIXFS_DATA")));
}

/// Returns the embedded Minix V3 filesystem image, or an empty slice.
pub fn minixfs_image() -> &'static [u8] {
    #[cfg(feature = "embed_minixfs")]
    {
        &generated::MINIXFS_IMG
    }
    #[cfg(not(feature = "embed_minixfs"))]
    {
        &[]
    }
}

/// Returns the length of the embedded Minix V3 filesystem image.
pub fn minixfs_image_len() -> usize {
    #[cfg(feature = "embed_minixfs")]
    {
        generated::MINIXFS_IMG_LEN
    }
    #[cfg(not(feature = "embed_minixfs"))]
    {
        0
    }
}
