//! Embedded Minix V3 filesystem image — used by the RAM disk driver.
//!
//! The image is generated by `tools/mkminixfs.rs` and written to
//! `target/minixfs_data.rs` by the build process.

/// Include the generated Minix FS image data.
///
/// The generated file (in `target/minixfs_data.rs`) defines:
/// - `MINIXFS_IMG: [u8; ...]` — the raw filesystem image
/// - `MINIXFS_IMG_LEN: usize` — its length
///
/// The path is workspace-relative: `crates/kernel/src/../../../target/minixfs_data.rs`
/// resolves to `target/minixfs_data.rs` from the project root.
#[cfg(feature = "embed_minixfs")]
mod generated {
    include!("../../../target/minixfs_data.rs");
}

/// Returns the embedded Minix V3 filesystem image, or an empty slice.
pub fn minixfs_image() -> &'static [u8] {
    #[cfg(feature = "embed_minixfs")]
    {
        &generated::MINIXFS_IMG
    }
    #[cfg(not(feature = "embed_minixfs"))]
    {
        &[]
    }
}

/// Returns the length of the embedded Minix V3 filesystem image.
pub fn minixfs_image_len() -> usize {
    #[cfg(feature = "embed_minixfs")]
    {
        generated::MINIXFS_IMG_LEN
    }
    #[cfg(not(feature = "embed_minixfs"))]
    {
        0
    }
}
