#!/usr/bin/env python3
"""Build the port's C++ runtime (libc++ + libc++abi) for one minix target.

    python tools/build-libcxx.py [x86|riscv64|aarch64]

Writes `target/cxx/<arch>/minix-runtime/libstdc++.a`, the one archive
`tools/cc-dso-minix.py` links into Mesa's shared objects. This is the sequence
`just libcxx-x86` used to spell out inline; the flags that differ per target
(the red zone, RISC-V's `-march`/`-mabi`) come from `tools/ccarch.py`, so they
agree with the C compiles `tools/cc-dso-minix.py` does for the same arch.

`libc++` builds against `target/cxx/toolchain-<machine>.cmake`, generated by
`tools/libcxx-toolchain.py` (called here). libc++abi is built with explicit
flags, because its cmake never reads the toolchain's `C_FLAGS_INIT`.
"""

from __future__ import annotations

import os
import pathlib
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from ccarch import Arch, resolve_argv  # noqa: E402

LIBCXX_SRC = ROOT / "rust" / "src" / "llvm-project" / "libcxx"
LIBCXXABI_SRC = ROOT / "rust" / "src" / "llvm-project" / "libcxxabi"
LIBCXX_INCLUDE = LIBCXX_SRC / "include"
LIBCXXABI_INCLUDE = LIBCXXABI_SRC / "include"


def root() -> str:
    return str(ROOT).replace("\\", "/")


def cxx_root(arch: Arch) -> pathlib.Path:
    return ROOT / "target" / "cxx" / arch.name


def host_flags(arch: Arch) -> list[str]:
    """The freestanding PIC flags a C/C++ object for this target needs.

    `-mno-red-zone` only where the arch has one (`ccarch.Arch.red_zone`), and
    RISC-V's `-march=rv64gc -mabi=lp64d` where the psABI default would disagree
    with the fork's `Lp64d` spec.
    """
    flags = ["-ffreestanding", "-fPIC"]
    if arch.red_zone:
        flags.append("-mno-red-zone")
    flags += list(arch.extra_cflags)
    return [*flags, "-fno-stack-protector"]


def run(cmd: list[object], cwd: pathlib.Path | None = None) -> int:
    print("+ " + " ".join(str(c) for c in cmd))
    return subprocess.run([str(c) for c in cmd], cwd=cwd).returncode


def need(name: str) -> str:
    found = shutil.which(name)
    if found is None:
        sys.exit(f"error: `{name}` not found on PATH (needed by the libc++ build)")
    return found


def main(argv: list[str]) -> int:
    arch, rest = resolve_argv(argv)
    if rest:
        sys.exit(f"error: unexpected argument {rest[0]!r}")
    cmake, ninja = need("cmake"), need("ninja")
    llvm_ar = need("llvm-ar")
    r = root()

    if run([sys.executable, str(ROOT / "tools" / "libcxx-toolchain.py"), arch.name]) != 0:
        return 1
    toolchain = ROOT / "target" / "cxx" / f"toolchain-{arch.machine}.cmake"

    base = cxx_root(arch)
    libcxx_build = base / "libcxx-build"
    libcxxabi_build = base / "libcxxabi-build"
    config = libcxx_build / "include" / "c++" / "v1"

    # The IWYU mapping step needs a Python that can import libcxx's local modules.
    # The host's is fine where it is a real CPython; on Windows the only python is
    # the embeddable one beside LLVM, whose `._pth` pins sys.path, so a stub .cmd
    # does the (unused) step instead.
    py = str(ROOT / "tools" / "libcxx-iwyu.cmd") if os.name == "nt" \
        else (sys.executable or "python3")

    for d in (libcxx_build, libcxxabi_build):
        shutil.rmtree(d, ignore_errors=True)

    libcxx_flags = f"-I{r}/rust/src/llvm-project/libcxxabi/include;-D_POSIX_TIMERS=200809L"
    if run([cmake, "-G", "Ninja", "-S", str(LIBCXX_SRC), "-B", str(libcxx_build),
            f"-DCMAKE_TOOLCHAIN_FILE={toolchain}", "-DCMAKE_BUILD_TYPE=Release",
            "-DLIBCXX_ENABLE_SHARED=OFF", "-DLIBCXX_ENABLE_STATIC=ON",
            "-DLIBCXX_ENABLE_EXCEPTIONS=OFF", "-DLIBCXX_ENABLE_RTTI=OFF",
            "-DLIBCXX_ENABLE_FILESYSTEM=OFF", "-DLIBCXX_ENABLE_LOCALIZATION=OFF",
            "-DLIBCXX_ENABLE_MONOTONIC_CLOCK=ON",
            "-DLIBCXX_ENABLE_NEW_DELETE_DEFINITIONS=OFF",
            "-DLIBCXX_ENABLE_RANDOM_DEVICE=ON", "-DLIBCXX_ENABLE_ABI_LINKER_SCRIPT=OFF",
            "-DLIBCXX_ENABLE_THREADS=ON", "-DLIBCXX_HAS_PTHREAD_API=ON",
            "-DLIBCXX_ABI_VERSION=1", "-DLIBCXX_ABI_NAMESPACE=__1",
            "-DLIBCXX_CXX_ABI=system-libcxxabi",
            f"-DLIBCXX_CXX_ABI_INCLUDE_PATHS={LIBCXXABI_INCLUDE}",
            "-DLIBCXX_AVAILABILITY_MINIMUM_HEADER_VERSION=2",
            "-DLIBCXX_SHARED_OUTPUT_NAME=cxx-shared", "-DLIBCXX_INCLUDE_TESTS=OFF",
            f"-DLIBCXX_ADDITIONAL_COMPILE_FLAGS={libcxx_flags}",
            f"-DPython3_EXECUTABLE={py}"]) != 0:
        return 1
    if run([ninja, "-C", str(libcxx_build)]) != 0:
        return 1

    cflags = " ".join([*host_flags(arch), "-O2", f"-I{r}/tools/c-include"])
    cxxflags = " ".join([*host_flags(arch), "-O2", "-std=c++23", "-nostdinc++",
                         f"-I{r}/rust/src/llvm-project/libcxx/include",
                         f"-I{r}/tools/c-include",
                         f"-I{r}/target/cxx/{arch.name}/libcxx-build/include/c++/v1"])
    if run([cmake, "-G", "Ninja", "-S", str(LIBCXXABI_SRC), "-B", str(libcxxabi_build),
            f"-DCMAKE_TOOLCHAIN_FILE={toolchain}", "-DCMAKE_BUILD_TYPE=Release",
            f"-DCMAKE_C_FLAGS={cflags}", f"-DCMAKE_CXX_FLAGS={cxxflags}",
            "-DLIBCXXABI_ENABLE_SHARED=OFF", "-DLIBCXXABI_ENABLE_STATIC=ON",
            "-DLIBCXXABI_BAREMETAL=ON", "-DLIBCXXABI_ENABLE_THREADS=OFF",
            "-DLIBCXXABI_ENABLE_EXCEPTIONS=OFF",
            "-DLIBCXXABI_ENABLE_NEW_DELETE_DEFINITIONS=ON",
            "-DLIBCXXABI_AVAILABILITY_MINIMUM_HEADER_VERSION=2",
            "-DLIBCXXABI_INCLUDE_TESTS=OFF", "-DLIBCXXABI_USE_LLVM_UNWINDER=OFF",
            "-DLIBCXXABI_ENABLE_STATIC_UNWINDER=OFF",
            "-DLIBCXXABI_SHARED_OUTPUT_NAME=cxxabi-shared"]) != 0:
        return 1
    if run([ninja, "-C", str(libcxxabi_build)]) != 0:
        return 1

    merge = base / "merge-tmp"
    runtime = base / "minix-runtime"
    shutil.rmtree(merge, ignore_errors=True)
    shutil.rmtree(runtime, ignore_errors=True)
    merge.mkdir(parents=True)
    for archive in (libcxxabi_build / "lib" / "libc++abi.a",
                    libcxx_build / "lib" / "libc++.a"):
        if run([llvm_ar, "x", str(archive)], cwd=merge) != 0:
            return 1
    runtime.mkdir(parents=True)
    objs = sorted(str(p) for p in merge.glob("*.obj"))
    return run([llvm_ar, "rcs", str(runtime / "libstdc++.a"), *objs], cwd=merge)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
