#!/usr/bin/env python3
"""Write `target/cxx/toolchain-x86_64.cmake`, the cross file `just libcxx-x86`
configures libc++/libc++abi with.

It lives under `target/` because it embeds the absolute repo path and clang's
resource directory, both machine-specific; this script is the tracked half that
regenerates it. Freestanding (`-nostdinc`), PIC (the runtime links into the Mesa
shared objects), and the port's C headers plus the libc++ headers in the order
`just libcxx-x86` documents.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]

TEMPLATE = """\
# Generated by tools/libcxx-toolchain.py — do not edit.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(MINIX_ROOT "{root}")
set(MINIX_TRIPLE x86_64-unknown-none)

find_program(MINIX_CLANG clang REQUIRED)
find_program(MINIX_CLANGXX clang++ REQUIRED)
find_program(MINIX_AR llvm-ar REQUIRED)
find_program(MINIX_RANLIB llvm-ranlib REQUIRED)

set(CMAKE_C_COMPILER "${{MINIX_CLANG}}")
set(CMAKE_CXX_COMPILER "${{MINIX_CLANGXX}}")
set(CMAKE_AR "${{MINIX_AR}}")
set(CMAKE_RANLIB "${{MINIX_RANLIB}}")
set(CMAKE_C_COMPILER_TARGET "${{MINIX_TRIPLE}}")
set(CMAKE_CXX_COMPILER_TARGET "${{MINIX_TRIPLE}}")

execute_process(COMMAND "${{MINIX_CLANG}}" -print-resource-dir
                OUTPUT_VARIABLE MINIX_CLANG_RES
                OUTPUT_STRIP_TRAILING_WHITESPACE)
set(MINIX_CLANG_INC "${{MINIX_CLANG_RES}}/include")

set(MINIX_C_FLAGS
    "-ffreestanding -fPIC -mno-red-zone -fno-stack-protector -O2 -nostdinc -isystem \\"${{MINIX_CLANG_INC}}\\" -I\\"${{MINIX_ROOT}}/tools/c-include\\"")
# Order matters: libc++ first, then the C headers, then the generated config dir
# the build adds itself (libc++'s <string.h> guard skips the C headers otherwise).
set(MINIX_CXX_FLAGS
    "${{MINIX_C_FLAGS}} -nostdinc++ -isystem \\"${{MINIX_ROOT}}/rust/src/llvm-project/libcxx/include\\" -isystem \\"${{MINIX_ROOT}}/rust/src/llvm-project/libcxxabi/include\\"")

set(CMAKE_C_FLAGS_INIT "${{MINIX_C_FLAGS}}")
set(CMAKE_CXX_FLAGS_INIT "${{MINIX_CXX_FLAGS}}")
"""


def main() -> int:
    root = str(ROOT).replace("\\", "/")
    out = ROOT / "target" / "cxx" / "toolchain-x86_64.cmake"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(root=root), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
