#!/usr/bin/env python3
"""Write `target/cxx/toolchain-<machine>.cmake`, the cross file `just libcxx
<arch>` configures libc++/libc++abi with.

It lives under `target/` because it embeds the absolute repo path and clang's
resource directory, both machine-specific; this script is the tracked half that
regenerates it. Freestanding (`-nostdinc`), PIC (the runtime links into the Mesa
shared objects), and the port's C headers plus the libc++ headers in the order
`just libcxx` documents.

Usage: python tools/libcxx-toolchain.py [x86|riscv64|aarch64]
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from ccarch import Arch, resolve_argv  # noqa: E402

# A literal backslash-quote, which cmake needs around a path inside a quoted
# value (`clang -print-resource-dir` can be `/Program Files/...`, spaces and all).
# Built from character codes so no backslash appears in this file's source.
_BS = chr(92)
_DQ = chr(34)


def quoted(text: str) -> str:
    return f"{_BS}{_DQ}{text}{_BS}{_DQ}"


# The C flags every libc++ target object needs. `-fPIC`, not the executable
# `-fno-pic` `arch.base_cflags()` carries: the runtime is linked into shared
# objects. The red-zone flag and RISC-V's `-march`/`-mabi` come from the arch, so
# a compile here agrees with the one `tools/cc-dso-minix.py` does for Mesa.
COMMON_TAIL = "-fno-stack-protector -O2 -nostdinc"


def c_flags(arch: Arch) -> str:
    flags = ["-ffreestanding", "-fPIC"]
    if arch.red_zone:
        flags.append("-mno-red-zone")
    flags += list(arch.extra_cflags)
    flags.append(COMMON_TAIL)
    flags.append("-isystem " + quoted("${MINIX_CLANG_INC}"))
    flags.append("-I" + quoted("${MINIX_ROOT}/tools/c-include"))
    return " ".join(flags)


def toolchain_text(arch: Arch) -> str:
    root = str(ROOT).replace("\\", "/")
    c = c_flags(arch)
    cxx = (f"{c} -nostdinc++ "
           "-isystem " + quoted("${MINIX_ROOT}/rust/src/llvm-project/libcxx/include") + " "
           "-isystem " + quoted("${MINIX_ROOT}/rust/src/llvm-project/libcxxabi/include"))
    out = f"""\
# Generated by tools/libcxx-toolchain.py — do not edit.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR {arch.machine})
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(MINIX_ROOT "{root}")
set(MINIX_TRIPLE {arch.clang_target})

find_program(MINIX_CLANG clang REQUIRED)
find_program(MINIX_CLANGXX clang++ REQUIRED)
find_program(MINIX_AR llvm-ar REQUIRED)
find_program(MINIX_RANLIB llvm-ranlib REQUIRED)

set(CMAKE_C_COMPILER "${{MINIX_CLANG}}")
set(CMAKE_CXX_COMPILER "${{MINIX_CLANGXX}}")
set(CMAKE_AR "${{MINIX_AR}}")
set(CMAKE_RANLIB "${{MINIX_RANLIB}}")
set(CMAKE_C_COMPILER_TARGET "${{MINIX_TRIPLE}}")
set(CMAKE_CXX_COMPILER_TARGET "${{MINIX_TRIPLE}}")

execute_process(COMMAND "${{MINIX_CLANG}}" -print-resource-dir
                OUTPUT_VARIABLE MINIX_CLANG_RES
                OUTPUT_STRIP_TRAILING_WHITESPACE)
set(MINIX_CLANG_INC "${{MINIX_CLANG_RES}}/include")

set(MINIX_C_FLAGS "{c}")
# Order matters: libc++ first, then the C headers, then the generated config dir
# the build adds itself (libc++'s <string.h> guard skips the C headers otherwise).
set(MINIX_CXX_FLAGS "{cxx}")

set(CMAKE_C_FLAGS_INIT "${{MINIX_C_FLAGS}}")
set(CMAKE_CXX_FLAGS_INIT "${{MINIX_CXX_FLAGS}}")
"""
    return out


def main(argv: list[str]) -> int:
    arch, rest = resolve_argv(argv)
    if rest:
        sys.exit(f"error: unexpected argument {rest[0]!r}")
    out = ROOT / "target" / "cxx" / f"toolchain-{arch.machine}.cmake"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(toolchain_text(arch), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
