#!/usr/bin/env python3
"""Regenerate the rust fork's `rust/config.toml` for the given minix arch.

Usage: python tools/rust-config.py [all|x86|riscv64|aarch64]   (default: all)

The fork's `config.toml` is gitignored, so `just bootstrap` calls this to
(re)create it deterministically before running x.py. The minix targets are
in STAGE0_MISSING_TARGETS, so bootstrap builds a stage1 compiler from
source; `download-ci-llvm` avoids a from-source LLVM build.

The build host triple is detected and always included in the target list:
x.py prunes std for any target not listed, and the host std is required to
run build scripts (e.g. the minixrs crates' build.rs) when compiling for a
minix target.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

ARCH_TO_TARGET = {
    "x86": "x86_64-pc-minix",
    "riscv64": "riscv64gc-unknown-minix",
    "aarch64": "aarch64-unknown-minix",
}


def detect_host() -> str:
    """Detect the build host triple via the default toolchain's rustc."""
    try:
        out = subprocess.run(
            ["rustc", "-vV"], capture_output=True, text=True, check=True
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""
    for line in out.splitlines():
        if line.startswith("host: "):
            return line[6:].strip()
    return ""


def main(argv: list[str]) -> int:
    arch = argv[1] if len(argv) > 1 else "all"
    if arch == "all":
        minix_targets = list(ARCH_TO_TARGET.values())
    elif arch in ARCH_TO_TARGET:
        minix_targets = [ARCH_TO_TARGET[arch]]
    else:
        print(
            f"error: unknown arch {arch!r}; expected all|x86|riscv64|aarch64",
            file=sys.stderr,
        )
        return 2

    host = detect_host()
    targets = ([host] if host else []) + minix_targets

    config = f"""# Generated by tools/rust-config.py ({arch}) — rerun `just bootstrap` to
# regenerate, or hand-edit (subsequent bootstrap runs overwrite it).
# The host ({host}) is always listed so its std survives x.py's pruning.

[llvm]
download-ci-llvm = true

[build]
target = {targets!r}
"""
    out = ROOT / "rust" / "config.toml"
    out.parent.mkdir(parents=True, exist_ok=True)
    # Explicit UTF-8: x.py reads config.toml as UTF-8, and the locale
    # encoding (cp1252 on Windows) would mangle non-ASCII bytes.
    out.write_text(config, encoding="utf-8")
    print(f"wrote {out} with targets {targets}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
