#!/usr/bin/env python3
"""Regenerate the rust fork's `rust/config.toml` for the given minix arch.

Usage: python tools/rust-config.py [all|x86|riscv64|aarch64]   (default: all)

The fork's `config.toml` is gitignored, so `just bootstrap` calls this to
(re)create it deterministically before running x.py. The minix targets are
in STAGE0_MISSING_TARGETS, so bootstrap builds a stage1 compiler from
source; `download-ci-llvm` avoids a from-source LLVM build.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

ARCH_TO_TARGET = {
    "x86": "x86_64-pc-minix",
    "riscv64": "riscv64gc-unknown-minix",
    "aarch64": "aarch64-unknown-minix",
}


def main(argv: list[str]) -> int:
    arch = argv[1] if len(argv) > 1 else "all"
    if arch == "all":
        targets = list(ARCH_TO_TARGET.values())
    elif arch in ARCH_TO_TARGET:
        targets = [ARCH_TO_TARGET[arch]]
    else:
        print(
            f"error: unknown arch {arch!r}; expected all|x86|riscv64|aarch64",
            file=sys.stderr,
        )
        return 2

    config = f"""# Generated by tools/rust-config.py ({arch}) — rerun `just bootstrap` to
# regenerate, or hand-edit (subsequent bootstrap runs overwrite it).

[llvm]
download-ci-llvm = true

[build]
target = {targets!r}
"""
    out = ROOT / "rust" / "config.toml"
    out.parent.mkdir(parents=True, exist_ok=True)
    # Explicit UTF-8: x.py reads config.toml as UTF-8, and the locale
    # encoding (cp1252 on Windows) would mangle non-ASCII bytes.
    out.write_text(config, encoding="utf-8")
    print(f"wrote {out} with targets {targets}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
